nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN-fallback}"

npmPublishRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.1.1.cjs

cacheFolder: .yarn/offline-cache

enableGlobalCache: false
